#
#  Created by Lukas Stahlbock in 2022
#  Copyright (c) 2022 IAV GmbH Ingenieurgesellschaft Auto und Verkehr. All rights reserved.
#
ARG IMAGE_RELEASE
FROM --platform=arm64 ${IMAGE_RELEASE}

WORKDIR /usr/local/bin
ENV LD_LIBRARY_PATH=/lib/aarch64-linux-gnu/:/usr/lib/aarch64-linux-gnu/:/usr/local/lib/:/lib/:/usr/lib/
ENTRYPOINT [ "./routingmanagerd" ]
